queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'Restore Packages'
  inputs:
    workingDir: TaggerV1

- task: Npm@1
  displayName: 'Run Build'
  inputs:
    command: custom
    workingDir: TaggerV1
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    workingDir: TaggerV1
    customCommand: 'run test'

- task: Npm@1
  displayName: 'Run Clean'
  inputs:
    command: custom
    workingDir: TaggerV1
    customCommand: 'run clean'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '**/test-*.xml'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Scripts'
  inputs:
    PathtoPublish: 'Scripts'
    ArtifactName: Scripts

- powershell: '@(".git*", ".vs*", "*.yaml", "Artifacts", "TaggerV1\ts*.json", "TaggerV1\Tests", "TaggerV1\test-*.xml") | ForEach-Object { Remove-Item -Path $_ -Force -Recurse -ErrorAction SilentlyContinue }'
  displayName: 'Clean Artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: ArtifactsTagger
